defaults:
  - defaults
  - _self_

name: balance_beam

base_height: 0.0
border_width: 1.0
border_height: ${terrain.base_height}

# Beam
beam_width:
  min: 1.5
  max: 0.3
beam_height: 
  min: 0.0 
  max: 0.0

# Pit
pit_height: 
  value: -0.40