width: 8.0
length: 8.0

horizontal_scale: 0.1
vertical_scale: 0.005
base_height: 0.0

border_width: 1.0
border_height: 1.0

slope_threshold: 0.75
seed: ${seed}

post:
  roughness:
    enabled: false
    amplitude: 0
    seed: ${seed}