width: 10.0
length: 10.0

horizontal_scale: 0.05
vertical_scale: 0.02
base_height: 0.0

border_width: 0.0
border_height: 0.0

slope_threshold: 0.075

post:
  roughness:
    enabled: true
    amplitude: 1
    seed: ${seed}