# configs/terrain/discrete_boxes.yaml

defaults:
  -  defaults
  - _self_

name: discrete_boxes

border_width: 0.5
border_height: ${terrain.base_height}

box_size: 
  min: 
    low: 0.1
    high: 0.45
  max: 
    low: 0.3
    high: 0.45


box_height: 
  min:
   low: 0.00
   high: 0.05
  max: 
    low: 0.10
    high: 0.20

platform_size: 
  value: 1.0