defaults:
  -  defaults
  - _self_

name: narrow_corridor

border_width: 1.0
border_height: ${terrain.base_height}

# Corridor
corridor_width: 
  min: 1.2
  max: 0.4

# Walls
wall_height: 
  min: 0.50
  max: 0.50
