defaults:
  -  defaults
  - _self_

name: narrow_corridor

border_width: 1.0
border_height: ${terrain.base_height}

# Corridor
corridor_width: 
  low: 1.2
  high: 0.4

# Walls
wall_height: 
  low: 0.50
  high: 0.50
