# configs/terrain/pyramid_slope.yaml

defaults:
  -  defaults
  - _self_

name: pyramid_slope

border_width: 1.0
border_height: ${terrain.base_height}

slope: 
  low: 0.2
  high: 0.2
platform_size: 
  low: 2.0
  high: 2.0
inverted: 
  value: false