# configs/terrain/pyramid_stairs.yaml

defaults:
  -  defaults
  - _self_

name: pyramid_stairs

border_width: 1.0
border_height: ${terrain.base_height}

step_width: 
  low: 0.5
  high: 0.3
step_height:
  low: 0.05
  high: 0.15
platform_size:
  low: 2.0
  high: 2.0

inverted: 
  value: false