# configs/terrain/pyramid_stairs.yaml

defaults:
  -  defaults
  - _self_

name: pyramid_stairs

border_width: 1.0
border_height: ${terrain.base_height}

step_width: 
  min: 0.8
  max: 0.5
step_height:
  min: 0.05
  max: 0.2
platform_size:
  min: 2.0
  max: 2.0

inverted: 
  value: false