# configs/terrain/pyramid_slope.yaml

defaults:
  -  defaults
  - _self_

name: pyramid_slope

border_width: 1.0
border_height: ${terrain.base_height}

slope: 
  min: 0.2
  max: 0.2
platform_size: 
  min: 2.0
  max: 2.0
inverted: 
  value: false