# configs/terrain/stairs.yaml

defaults:
  -  defaults
  - _self_

name: stairs

border_width: 1.0
border_height: ${terrain.base_height}

step_width: 
  low: 0.8
  high: 0.5
step_height:
  low: 0.05
  high: 0.2

direction:
  choices: ["x", "y"]
  probs: [0.5, 0.5]