# configs/terrain/stepping_stones.yaml

defaults:
  -  defaults
  - _self_

name: stepping_stones

stone_w: [0.8, 0.3]
stone_l: [0.8, 0.3]
spacing_w: [0.05, 0.15]
spacing_l: [0.05, 0.15]

stone_height: 0.0
base_height: -0.25

border_width: 1.0
border_height: 0.0

randomize_pos: true
