# configs/terrain/stepping_stones.yaml

defaults:
  -  defaults
  - _self_

name: stepping_stones

stone_size: [0.3, 0.3]
spacing: [0.15, 0.15]

stone_height: 0.0
base_height: -0.25

border_width: 1.0
border_height: 0.0
